// barrel file
export * from './page1/page1.component'
export * from './page2/page2.component'
export * from './page2/chapter.component'
export * from './page3/page3.component'
export * from './page3/counter.component'
export * from './page3/timer.component'
export * from './page4/page4.component'
export * from './pages.routs'
export * from './pages.module'
